### PR TITLE
[Kernel] Fix schema id population for iceberg compat v2

### LINKED ISSUE #4535: [BUG][Kernel] Kernel does not appropriately assign field IDs for arrays and maps that are nested with each other
#### Which Delta project/connector is this regarding?
- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Describe the problem

Kernel does not appropriately assign field IDs for arrays and maps that are nested with each other for icebergCompatV2. They end up adding in new field id that aren't used causing maxFieldId to be needlessly added.

#### Steps to reproduce

Create a schema like `StructField('e', Array<Map<string, String>>)` and try to assign field IDs to it.  In this case the metadata for the nested `Map` is ignored.

#### Observed results

We miss keeping some metadata that we should.

#### Expected results

Metadata to properly be read.

#### Further details

N/A

### Environment information

* Delta Lake version:
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by emkornfield**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

## Description

This PR fixes how nested field IDs are populated on metadata.  Before this change metadata was added directly to the parent StructField no matter how deeply maps/arrays where nested.  With this change we populate metadata correctly on the near parent StructField (ignoring intermediate StructFields  in Maps/Array which are just a nicety for the schema object model).  This also has the impact of not incrementing max field ID for pre-populated fields.

Resolve #4535

## How was this patch tested?

Added unit tests/existing tests.

## Does this PR introduce _any_ user-facing changes?

It fixes a bug.

### CODE REVIEW

File: kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala [hunk 1]
```diff
@@ -515,6 +519,73 @@ class ColumnMappingSuite extends AnyFunSuite with ColumnMappingSuiteBase {
...
+      val expectedMetadata = FieldMetadata.builder().putFieldMetadata(COLUMN_MAPPING_NESTED_IDS_KEY, nestedColumnMappingValues)
+        .putString("delta.columnMapping.physicalName", prefix)
+        .putLong("delta.columnMapping.id", base)
+        .putBoolean("k2", true).build()
+      val firstColumnMetadata = getter(metadata).getMetadata
+      assertThat(firstColumnMetadata.getMetadata(COLUMN_MAPPING_NESTED_IDS_KEY).getEntries).containsExactlyInAnyOrderEntriesOf(nestedColumnMappingValues.getEntries)
+      assertThat(firstColumnMetadata.getEntries).containsExactlyInAnyOrderEntriesOf(expectedMetadata.getEntries)
+
+        // TODO: It would be nice to have visitor pattern on schema so we can assert all metadata for nested fields
+        // are empty but this at least provides a sanity check.
```
Comment (amogh-jahagirdar) [inline kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala]: yeah the visitor pattern is on me :( once I finish the schema evo test PR, I'll have a PR out for visitor

File: kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala [hunk 2]
```diff
@@ -515,6 +519,93 @@ class ColumnMappingSuite extends AnyFunSuite with ColumnMappingSuiteBase {
...
+
+          // TODO: It would be nice to have visitor pattern on schema so we can assert
+          // all metadata for nested fields
+          // are empty but this at least provides a sanity check.
+          assert(getter(metadata).getDataType.asInstanceOf[
+            ArrayType].getElementField.getMetadata == FieldMetadata.empty())
+
+          // Requesting the same operation on the same schema shouldn't change anything
+          // as the schema already has the necessary column mapping info
+          assertNoOpOnUpdateColumnMappingMetadataRequest(
```
Comment (amogh-jahagirdar) [inline kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala:601]: If I follow this assertion implicitly validates that if pre-assigned IDs were passed to the schema that's being set, that we're not doing any column mapping update or max field ID update right?  Basically asserting we are hitting https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java#L380 as expected

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks @emkornfield!

File: kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala (hunk 2 above)
Comment (allisonport-db) [reply kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala:601]: +1 also wondered the same thing - maybe add a comment "this also validates that the maxFieldId is not updated" just for future clarity?

File: kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala
Comment (allisonport-db) [inline kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala:1]: We didn't catch this in existing tests since cmTestInfo doesn't have the double nested array/map right?

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala [hunk 3]
```diff
@@ -296,7 +296,11 @@ class DeltaTableSchemaEvolutionSuite extends DeltaTableWriteSuiteBase with Colum
       assertColumnMapping(structType.get("a"), 1)
       assertColumnMapping(structType.get("map"), 4, "map")
       assert(structType.get("map").getMetadata.get(ColumnMapping.COLUMN_MAPPING_NESTED_IDS_KEY)
-        == FieldMetadata.builder().putLong("map.key", 5).putLong("map.value", 6).build())
+        == FieldMetadata.builder()
+          .putLong("map.key", 5)
+          .putLong("map.value", 6)
+          .putLong("map.value.element", 7)
+          .build())
```
Comment (allisonport-db) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala:303]: nit - add a check for the maxFieldId here as well for thoroughness?

**Review by allisonport-db — APPROVED** [review]
LGTM with just a few minor suggestions

File: kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java [hunk 4]
```diff
@@ -573,16 +577,28 @@ private static StructType rewriteFieldIdsForIceberg(StructType schema, AtomicInt
    * @param structField The field where to start from
    * @param path The current field path relative to the parent field (aka most recent ancestor with
    *     a StructField). An empty path indicates that there's no parent and we're at the root
+   * @param closestStructFieldParentMetadata The metadata builder of the closest struct field parent
```
[the remark this answers is not in the document]
Comment (emkornfield) [reply kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java:580]: tried to add a few sentences.

File: kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java [hunk 5]
```diff
@@ -658,46 +682,28 @@ private static StructField transformSchema(
...
+   * @param field The FieldMetadata.Builder to update with nested IDs
    * @param key For a map this is <colName>.key or <colName>.value. For an array this is
    *     <colName>.element
    * @param currentFieldId The current maximum field id to increment and use for assignment
-   * @return A field with potentially updated {@link FieldMetadata}
    */
-  private static StructField maybeUpdateFieldId(
-      StructField field, String key, AtomicInteger currentFieldId) {
+  private static void maybeUpdateFieldId(
+      FieldMetadata.Builder field, String key, AtomicInteger currentFieldId) {
```
[the remark this answers is not in the document]
Comment (emkornfield) [reply kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java]: done

File: kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala
Comment (emkornfield) [reply kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala:1]: right, no doubly nested values.

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala (hunk 3 above)
Comment (emkornfield) [reply kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala:304]: done.

**Review by vkorukanti — APPROVED** [review]
