### PR TITLE
[Fix][Spark] REORG TABLE fails with NoSuchMethodError in Delta 4.0.0 with Spark 4.0.1 (master)

### LINKED ISSUE #5690: [BUG] REORG TABLE fails with NoSuchMethodError in Delta 4.0.0 with Spark 4.0.1
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem

The REORG TABLE APPLY (PURGE) command fails with NoSuchMethodError for tables with deletion vectors enabled. This error seems to occur only in Delta 4.0.0 with Spark 4.0.1. It was not observed with Delta 4.0.0 and Spark 4.0.0. This error seems because of the signature change of `ParquetToSparkSchemaConverter` between Spark 4.0.0 and 4.0.1.

#### Steps to reproduce

Run this code.

```python
        from delta import DeltaTable
        spark.range(1000).withColumnRenamed('id', 'l_id').join(spark.range(10)).write.partitionBy('l_id').format('delta').option('delta.enableDeletionVectors', True).save('/tmp/range_dvp4')
        spark.sql("DELETE FROM delta.`/tmp/range_dvp4` WHERE id = 1")
        spark.sql("REORG table delta.`/tmp/range_dvp4` APPLY (PURGE)")
```

#### Observed results

The following error was thrown:

```
java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(boolean, boolean, boolean, boolean, boolean)
```

#### Expected results

The reorg command should succeed.

#### Further details

Here is a full stack trace.

```
E                   Caused by: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(boolean, boolean, boolean, boolean, boolean)'
E                   	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles(ReorgTableHelper.scala:149)
E                   	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles$(ReorgTableHelper.scala:122)
E                   	at org.apache.spark.sql.delta.commands.DeltaPurgeOperation.filterParquetFiles(DeltaReorgTableCommand.scala:108)
E                   	at org.apache.spark.sql.delta.commands.ReorgTableHelper.$anonfun$filterParquetFilesOnExecutors$1(ReorgTableHelper.scala:118)
E                   	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:901)
E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:901)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
E                   	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
E                   	at org.apache.spark.scheduler.Task.run(Task.scala:147)
E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
E                   	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
E                   	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
E                   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
E                   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
E                   	... 1 more
```

### Environment information

* Delta Lake version: 4.0.0
* Spark version: 4.0.1
* Scala version: 2.13

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by AnudeepKonaboina**
#### Which Delta project/connector is this regarding?
- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

When running `REORG TABLE … APPLY (PURGE)` on tables with Deletion Vectors enabled on a delta table when Delta is used with Spark 4.0.1, we get the following error 

### **Error message with stack trace:** 

```
py4j.protocol.Py4JJavaError: An error occurred while calling o35.sql.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 27.0 failed 1 times, most recent failure: Lost task 6.0 in stage 27.0 (TID 378) (192.168.0.103 executor driver): java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(boolean, boolean, boolean, boolean, boolean)'
	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles(ReorgTableHelper.scala:149)
	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles$(ReorgTableHelper.scala:122)
	at org.apache.spark.sql.delta.commands.DeltaPurgeOperation.filterParquetFiles(DeltaReorgTableCommand.scala:108)
	at org.apache.spark.sql.delta.commands.ReorgTableHelper.$anonfun$filterParquetFilesOnExecutors$1(ReorgTableHelper.scala:118)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:901)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
	at org.apache.spark.scheduler.Task.run(Task.scala:147)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

- Delta code instantiates ParquetToSparkSchemaConverter using a constructor form that compiles down to a call to Spark’s primary constructor (with default parameters).
 
- Spark 4.0.1 changed the ParquetToSparkSchemaConverter primary constructor signature (added an extra argument), so the constructor that Delta was compiled against is no longer present at runtime.

  - **Spark 4.0.0**: primary ctor has 5 boolean params (with defaults). [GitHub](https://github.com/apache/spark/raw/v4.0.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala)
  
  - **Spark 4.0.1**: primary ctor has 6 boolean params (added **useFieldId**). [GitHub](https://github.com/apache/spark/raw/v4.0.1/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala)

#### Environment information
- Delta Lake version: 4.0.0
- Spark version: 4.0.1
- Scala version: 2.13

### Where in the code this happens?

In [Delta 4.0.0](https://github.com/delta-io/delta/raw/v4.0.0/spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala), `ReorgTableHelper.filterParquetFiles` creates the converter like this:
`val converter = new ParquetToSparkSchemaConverter(assumeBinaryIsString, assumeInt96IsTimestamp) `

#### **Fix Made:**

Instead of calling the evolving primary constructor, this PR constructs ParquetToSparkSchemaConverter using the stable **SQLConf-based** constructor (`new ParquetToSparkSchemaConverter(SQLConf.get)`), which avoids binary incompatibility across Spark patch releases and keeps conversion behavior driven by Spark SQL configs.

This makes REORG TABLE … APPLY (PURGE) work on Spark 4.0.1 without impacting behavior on earlier Spark versions.

Fixes #5690 

## How was this patch tested?

- Made the code changes as described above and build the jar locally and ran the same code in the bug description using pyspark

```
((venv) ) anudeep.konaboina@JVXG0HHKCW spark-with-hadoop-anywhere % pyspark \                 
  --jars /Users/anudeep.konaboina/workspace/spark/github/delta/spark-unified/target/scala-2.13/delta-spark-assembly-4.1.0-SNAPSHOT.jar \
  --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
  --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
Python 3.12.10 (v3.12.10:0cc81280367, Apr  8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
WARNING: Using incubator modules: jdk.incubator.vector
25/12/15 19:45:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 4.0.1
      /_/

Using Python version 3.12.10 (v3.12.10:0cc81280367, Apr  8 2025 08:46:59)
Spark context Web UI available at http://192.168.0.103:4040
Spark context available as 'sc' (master = local[*], app id = local-1765808113238).
SparkSession available as 'spark'.
>>> spark.range(1000).withColumnRenamed("id","l_id").join(spark.range(10)) \
...   .write.partitionBy("l_id").format("delta") \
...   .option("delta.enableDeletionVectors", "true") \
...   .mode("overwrite").save("/tmp/range_dvp_fix_1")

>>> spark.sql("DELETE FROM delta.`/tmp/range_dvp_fix_1` WHERE id = 1")          
25/12/15 19:45:47 WARN ObjectStore: Failed to get database delta, returning NoSuchObjectException
25/12/15 19:45:48 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
DataFrame[num_affected_rows: bigint]                 
                           
>>> spark.sql("REORG TABLE delta.`/tmp/range_dvp_fix_1` APPLY (PURGE)")
25/12/15 19:46:01 WARN ObjectStore: Failed to get database delta, returning NoSuchObjectException
DataFrame[path: string, metrics: struct<numFilesAdded:bigint,numFilesRemoved:bigint,filesAdded:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,filesRemoved:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,partitionsOptimized:bigint,zOrderStats:struct<strategyName:string,inputCubeFiles:struct<num:bigint,size:bigint>,inputOtherFiles:struct<num:bigint,size:bigint>,inputNumCubes:bigint,mergedFiles:struct<num:bigint,size:bigint>,numOutputCubes:bigint,mergedNumCubes:bigint>,clusteringStats:struct<inputZCubeFiles:struct<numFiles:bigint,size:bigint>,inputOtherFiles:struct<numFiles:bigint,size:bigint>,inputNumZCubes:bigint,mergedFiles:struct<numFiles:bigint,size:bigint>,numOutputZCubes:bigint>,numBins:bigint,numBatches:bigint,totalConsideredFiles:bigint,totalFilesSkipped:bigint,preserveInsertionOrder:boolean,numFilesSkippedToReduceWriteAmplification:bigint,numBytesSkippedToReduceWriteAmplification:bigint,startTimeMs:bigint,endTimeMs:bigint,totalClusterParallelism:bigint,totalScheduledTasks:bigint,autoCompactParallelismStats:struct<maxClusterActiveParallelism:bigint,minClusterActiveParallelism:bigint,maxSessionActiveParallelism:bigint,minSessionActiveParallelism:bigint>,deletionVectorStats:struct<numDeletionVectorsRemoved:bigint,numDeletionVectorRowsRemoved:bigint>,numTableColumns:bigint,numTableColumnsWithStats:bigint>]
>>> 

```

No new unit tests were added in this PR (the issue is a Spark patch-level binary-compatibility failure that reproduces reliably via the end-to-end command path above).

## Does this PR introduce _any_ user-facing changes?

Yes.

Previously, users running Spark 4.0.1 with DV-enabled tables could hit a runtime NoSuchMethodError when executing REORG TABLE … APPLY (PURGE). With this change, the command runs successfully by using the stable SQLConf-based Parquet schema converter constructor.

### CODE REVIEW

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala
Comment (gerashegalov) [inline spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: no longer used

we might need to pass in `spark: SparkSession` instead

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala [hunk 1]
```diff
@@ -145,8 +146,9 @@ trait ReorgTableHelper extends Serializable {
       fileStatuses.toList,
       ignoreCorruptFiles)
 
-    val converter =
-      new ParquetToSparkSchemaConverter(assumeBinaryIsString, assumeInt96IsTimestamp)
+    // Spark 4.0.1 changed the primary ctor signature (added a param), which breaks binary
+    // compatibility for code compiled against Spark 4.0.0. Use the stable SQLConf ctor instead.
+    val converter = new ParquetToSparkSchemaConverter(SQLConf.get)
```
Comment (gerashegalov) [inline spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: There does not seem to be a way to achieve 100% equivalency to the prior code using this constructor. But in spirit of the previous code it should be the current `SessionState.conf` passed in here. 
```suggestion
    val converter = new ParquetToSparkSchemaConverter(spark.sessionState.conf)
```

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala
Comment (AnudeepKonaboina) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: Agreed @gerashegalov ! i saw that in the morning today and made the change already .. just need to test it before pushing it .


Passing spark directly might not be a solution here  since sending spark object inside mapPartitions runs on executors, so the closure is serialised and sparkSession is not serializable. We might just need to pass the `spark.sessionState.conf` captured on the driver as sqlConf

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala (hunk 1 above)
Comment (AnudeepKonaboina) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: Yeah ! same here  i see that **SQLConf.get** relies on the thread-local active conf and may not reflect the current SparkSession’s effective SQL configs. 

As mentioned above , i would push these changes once i test it out . Below are the changes made :

- _**spark.sessionState.conf**_ is captured  as **_sqlConf_** and
- passed to filterParquetFiles method

Comment (johanl-db) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: @AnudeepKonaboina did you get around to implement this? I don't think I see in the latest changes.

Since `SQLConf` is serializable, you should be able to pass the conf from the origin spark session inside `mapPartitions`:
```
    val sqlConf = spark.sessionState.conf
    files.toDF(spark).as[AddFile].mapPartitions { iter =>
        filterParquetFiles(
          sqlConf,
          iter.toList,
          dataPath,
          serializedConf.value,
          ignoreCorruptFiles)(filterFileFn).toIterator
    }.collect()
```
that way we don't rely on SparkSession.active on the executor, which can technically return a session that's different than the one we passed to `filterParquetFilesOnExecutors` I believe.

**Comment by johanl-db** [comment]
There's a release for Delta 4.0.1 being prepared, we should get this change in.
@AnudeepKonaboina can you also create a PR against [branch-4.0](https://github.com/delta-io/delta/tree/branch-4.0) in addition to `master`?

cc @TimothyW553: I hope it's not too late to catch the release train, we should try to include that fix in the 4.0.1 release otherwise REORG will be broken

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala (hunk 1 above)
Comment (AnudeepKonaboina) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: Hey @johanl-db ,

Hey @johanl-db ! I initially  tried modifying the code same as the above:

```
val sqlConf = spark.sessionState.conf
    files.toDF(spark).as[AddFile].mapPartitions { iter =>
        filterParquetFiles(
          sqlConf,
          iter.toList,
          dataPath,
          serializedConf.value,
          ignoreCorruptFiles)(filterFileFn).toIterator
    }.collect()
```

But when we I run the testSuite i  get the below error in `TypeWideningTableFeaturePreviewSuite` and `RowTrackingPurgeSuite`
```
./build/sbt "spark/testOnly org.apache.spark.sql.delta.DeltaGenerateSymlinkManifestSuite org.apache.spark.sql.delta.typewidening.TypeWideningTableFeaturePreviewSuite org.apache.spark.sql.delta.rowid.RowTrackingPurgeSuite"
```
**_ERROR:_**
```
[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 158.0 failed 1 times, most recent failure: Lost task 0.0 in stage 158.0 (TID 145) (192.168.0.103 executor driver): java.lang.NullPointerException: Cannot invoke "org.apache.spark.internal.config.ConfigReader.get(String)" because "reader" is null
[info] 	at org.apache.spark.internal.config.ConfigEntry.readString(ConfigEntry.scala:96)
[info] 	at org.apache.spark.internal.config.ConfigEntryWithDefault.readFrom(ConfigEntry.scala:141)
[info] 	at org.apache.spark.sql.internal.SQLConf.getConf(SQLConf.scala:6661)
[info] 	at org.apache.spark.sql.internal.SQLConf.isParquetBinaryAsString(SQLConf.scala:6120)
[info] 	at org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(ParquetSchemaConverter.scala:64)
[info] 	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles(ReorgTableHelper.scala:154)
[info] 	at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFiles$(ReorgTableHelper.scala:126)
[info] 	at org.apache.spark.sql.delta.commands.DeltaPurgeOperation.filterParquetFiles(DeltaReorgTableCommand.scala:108)
[info] 	at org.apache.spark.sql.delta.commands.ReorgTableHelper.$anonfun$filterParquetFilesOnExecutors$1(ReorgTableHelper.scala:122)
[info] 	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
[info] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:901)
[info] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:901)
[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
[info] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[info] 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[info] 	at org.apache.spark.scheduler.Task.run(Task.scala:147)
[info] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[info] 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[info] 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[info] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[info] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info] 	at java.base/java.lang.Thread.run(Thread.java:840)
[info] 
[info] Driver stacktrace:
[info]   at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$3(DAGScheduler.scala:2935)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2935)
[info]   at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2927)
[info]   at scala.collection.immutable.List.foreach(List.scala:334)
[info]   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2927)
[info]   at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1295)
[info]   at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1295)
[info]   at scala.Option.foreach(Option.scala:437)
[info]   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1295)
[info]   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3207)
[info]   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3141)
[info]   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3130)
[info]   at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)
[info]   at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1009)
[info]   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2484)
[info]   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2505)
[info]   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2524)
[info]   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2549)
[info]   at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1057)
[info]   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[info]   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[info]   at org.apache.spark.rdd.RDD.withScope(RDD.scala:417)
[info]   at org.apache.spark.rdd.RDD.collect(RDD.scala:1056)
[info]   at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:462)
[info]   at org.apache.spark.sql.classic.Dataset.collectFromPlan(Dataset.scala:2244)
[info]   at org.apache.spark.sql.classic.Dataset.$anonfun$collect$1(Dataset.scala:1482)
[info]   at org.apache.spark.sql.classic.Dataset.$anonfun$withAction$2(Dataset.scala:2234)
[info]   at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:654)
[info]   at org.apache.spark.sql.classic.Dataset.$anonfun$withAction$1(Dataset.scala:2232)
[info]   at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$8(SQLExecution.scala:163)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:272)
[info]   at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$7(SQLExecution.scala:125)
[info]   at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
[info]   at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:112)
[info]   at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:106)
[info]   at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:111)
[info]   at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$6(SQLExecution.scala:125)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:295)
[info]   at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:124)
[info]   at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:78)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:237)
[info]   at org.apache.spark.sql.classic.Dataset.withAction(Dataset.scala:2232)
[info]   at org.apache.spark.sql.classic.Dataset.collect(Dataset.scala:1482) 
[info]    at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFilesOnExecutors(ReorgTableHelper.scala:116)
[info]   at org.apache.spark.sql.delta.commands.ReorgTableHelper.filterParquetFilesOnExecutors$(ReorgTableHelper.scala:103)
[info]   at org.apache.spark.sql.delta.commands.DeltaPurgeOperation.filterParquetFilesOnExecutors(DeltaReorgTableCommand.scala:108)
[info]   at org.apache.spark.sql.delta.commands.DeltaPurgeOperation.filterFilesToReorg(DeltaReorgTableCommand.scala:116)
[info]   at org.apache.spark.sql.delta.commands.OptimizeExecutor.$anonfun$optimize$1(OptimizeTableCommand.scala:307)
[info]   at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:171)
[info]   at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:169)
[info]   at org.apache.spark.sql.delta.commands.OptimizeExecutor.recordFrameProfile(OptimizeTableCommand.scala:251)
[info]   at org.apache.spark.sql.delta.metering.DeltaLogging.$anonfun$recordDeltaOperationInternal$1(DeltaLogging.scala:139)
[info]   at com.databricks.spark.util.DatabricksLogging.recordOperation(DatabricksLogging.scala:128)

```

This is because when **SQLConf** instance is getting captured and serialized into the mapPartitions, it contains a config reader which doesn't get serialized and  **ConfigEntry.readString** is returning a **null**
and hence i had switched to using `SparkSession.active.sessionState.conf`

Comment (johanl-db) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala]: That's unfortunate.. let's keep what you had before then

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala [hunk 2]
```diff
@@ -107,25 +108,27 @@ trait ReorgTableHelper extends Serializable {
...
-    val assumeBinaryIsString = spark.sessionState.conf.isParquetBinaryAsString
-    val assumeInt96IsTimestamp = spark.sessionState.conf.isParquetINT96AsTimestamp
     val dataPath = new Path(snapshot.deltaLog.dataPath.toString)
 
     import org.apache.spark.sql.delta.implicits._
 
     files.toDF(spark).as[AddFile].mapPartitions { iter =>
-        filterParquetFiles(iter.toList, dataPath, serializedConf.value, ignoreCorruptFiles,
-          assumeBinaryIsString, assumeInt96IsTimestamp)(filterFileFn).toIterator
+      val sqlConf = SparkSession.active.sessionState.conf
```
Comment (Kimahriman) [inline spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala:116]: This is running on the executor so it isn't valid, you can't get a SparkSession. It might pass in tests since tasks run in the same driver process, but when running this distributed it fails

**Comment by Kimahriman** [comment]
Also kindly request review of https://github.com/delta-io/delta/pull/5782, which between that issue and this still not working tables with DVs could grow unbounded

File: spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala (hunk 2 above)
Comment (AnudeepKonaboina) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala:116]: Hey @Kimahriman ,

The body of mapPartitions { … } runs on executors. If you referenced the driver spark inside that closure, Spark would try to serialize it (which is bad and invalid). That’s why we avoid using it there.

So Inside the executor closure we do:
**val sqlConf = SparkSession.active.sessionState.conf**

That is the executor-side active SparkSession for that running task, i.e., the session Spark sets as “active” while executing the query plan. So the converter uses executor/session config for the job, not the driver object.

We have tested this on a cluster with two executors and it works without any issues. Please let us know what error are you facing when you run REORG on a cluster with this change

Comment (Kimahriman) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala:116]:
```
% uvx --from pyspark==4.0.1 pyspark --packages io.delta:delta-spark_2.13:4.0.1 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" --master "local-cluster[2, 1, 1024]"
Python 3.14.2 (main, Dec  5 2025, 16:49:16) [Clang 17.0.0 (clang-1700.4.4.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
...
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 4.0.1
      /_/

Using Python version 3.14.2 (main, Dec  5 2025 16:49:16)
Spark context available as 'sc' (master = local-cluster[2, 1, 1024], app id = app-20260116063644-0000).
SparkSession available as 'spark'.
>>> spark.range(10).write.format('delta').save('/tmp/test-reorg')
>>> spark.sql('REORG TABLE delta.`/tmp/test-reorg` APPLY (PURGE)')
...
org.apache.spark.SparkException: [INTERNAL_ERROR] No active or default Spark session found SQLSTATE: XX000
	at org.apache.spark.SparkException$.internalError(SparkException.scala:92)
	at org.apache.spark.SparkException$.internalError(SparkException.scala:96)
	at org.apache.spark.sql.SparkSessionCompanion.$anonfun$active$2(SparkSession.scala:1031)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.sql.SparkSessionCompanion.$anonfun$active$1(SparkSession.scala:1031)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.sql.SparkSessionCompanion.active(SparkSession.scala:1030)
	at org.apache.spark.sql.delta.commands.ReorgTableHelper.$anonfun$filterParquetFilesOnExecutors$1(ReorgTableHelper.scala:116)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:901)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
	at org.apache.spark.scheduler.Task.run(Task.scala:147)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

> That is the executor-side active SparkSession for that running task, i.e., the session Spark sets as “active” while executing the query plan. So the converter uses executor/session config for the job, not the driver object.

Where does that happen? I can't find that anywhere in the code where an executor sets the SparkSession for a task

Comment (Kimahriman) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala:116]: Same thing happens on latest master with Spark 4.1
```
uvx --from pyspark==4.1.0 pyspark --packages io.delta:delta-spark_4.1_2.13:4.1.0-SNAPSHOT --conf "spark.sql.e
xtensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
 --master "local-cluster[2, 1, 1024]"
```

So not really sure how you got it to work distributed

Comment (AnudeepKonaboina) [reply spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala:116]: Ah! I Let me re-check this  again and re-run it on a cluestr .Will get back to you once i do the test again
