### PR TITLE
[#3423] Fix unnecessary DynamoDB GET calls during LogStore::listFrom VACUUM calls

### LINKED ISSUE #3423: [BUG] ProvisionedThroughputExceededException when performing VACUUM using S3DynamoDBLogStore
#### Which Delta project/connector is this regarding?

- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

#### Steps to reproduce

Perform VACUUM on a table configured to use the S3DynamoDBLogStore

#### Observed results

ProvisionedThroughputExceededException caused by:

```
at io.delta.storage.S3DynamoDBLogStore.getLatestExternalEntry(S3DynamoDBLogStore.java:185)
at io.delta.storage.BaseExternalLogStore.listFrom(BaseExternalLogStore.java:113)
```

#### Expected results

VACUUM shouldn't cause throughput-exceeded exception on the DynamoDB table.

### Environment information

* Delta Lake version: 3.2.0
* Spark version: 3.5.1
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [X] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by scottsand-db**
#### Which Delta project/connector is this regarding?

- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

Resolves #3423.

This PR updates the logic in `BaseExternalLogStore::listFrom` so that it does not make a request to get the latest entry from the external store (which is used to perform recovery operations) in the event that a non `_delta_log` file is being listed.

This is useful for VACUUM operations which may do hundreds or thousands of list calls in the table directory and nested partition directories of parquet files. This is NOT the `_delta_log`. Thus, checking the external store during these list calls is (1) useless and unwanted as we are not listing the `_delta_log` so clearly now isn't the time to attempt to do a fixup, and (2) expensive.

This PR makes it so that future VACUUM operations do not perform unnecessary calls to the external store (e.g. DyanamoDB).

## How was this patch tested?

Unit tests and an integration test that actually runs VACUUM and compares the number of external store calls using the old/new logic. I ran that test myself 50 times, too, and it passed every time (therefore, not flaky).

## Does this PR introduce _any_ user-facing changes?

No

### CODE REVIEW

File: storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java [hunk 1]
```diff
@@ -128,14 +129,19 @@ public BaseExternalLogStore(Configuration hadoopConf) {
...
+        if (isDeltaLogPath(resolvedPath)) {
+            final Path tablePath = getTablePath(resolvedPath);
+            final Optional<ExternalCommitEntry> entry = getLatestExternalEntry(tablePath);
+
+            if (entry.isPresent() && !entry.get().complete) {
+                // Note: `fixDeltaLog` will apply per-JVM mutual exclusion via a lock to help reduce
+                // the chance of many reader threads in a single JVM doing duplicate copies of
+                // T(N) -> N.json.
+                fixDeltaLog(fs, entry.get());
+            }
```
Comment (scottsand-db) [inline storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java:144]: only indentation change

**Review by vkorukanti — APPROVED** [review]

**Comment by scottsand-db** [comment]
The 6 Spark Master test failures are unrelated:

```
and expression - deterministic false - subquery false *** FAILED ***

(various similar tests)
```

https://github.com/delta-io/delta/actions/runs/10147582136/job/28058303844?pr=3425

**Review by raveeram-db — COMMENTED** [review]
LGTM!
