### PR TITLE
[Spark] Fix metadata cleanup by retaining files required for log reconstruction

### LINKED ISSUE #606: MetadataCleanUp may make the present versions not available
MetadataCleanup will delete the expired delta logs(json and checkpoint.parquet). But if the present version depends on these which will be cleaned up, it cannot replay to the whole commits. For example: we have delta logs from version 0 to version 10 as following: 000.json ~ 009.json, 010.json, 010.checkpoint.parquet.

When Commit 10 is operated, MetadataCleanup works. If we assume the logs before 9 (not contained) should be cleaned up, then the rest files are: 009.json, 010.json, 010.checkpoint.parquet.
In fact, Version 9 is not  available, and only Version 10 is shown by `desc history`.

### PR DESCRIPTION
**Pull request by felipepessoto**
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description
Delete eligible delta log files only if there's a checkpoint newer than them before the cutoff window.

Resolves #606

Unit tests based on https://github.com/delta-io/delta/pull/2673

## How was this patch tested?
Unit Tests

## Does this PR introduce _any_ user-facing changes?
Yes, tables with low rate of commit/checkpoints will have increased log retention beyond the cutoff window

### CODE REVIEW

**Comment by felipepessoto** [comment]
@andreaschat-db, could you help with the `Metadata cleanup respects requireCheckpointProtectionBeforeVersion` test failure, please?

I couldn't find any info in Delta protocol about checkpointProtection table feature

```
[info] - Metadata cleanup respects requireCheckpointProtectionBeforeVersion *** FAILED ***
[info]   HashSet(10, 14, 6, 9, 13, 12, 7, 11, 8, 15) did not equal HashSet(10, 14, 9, 13, 12, 11, 8, 15) (CheckpointProtectionTestUtilsMixin.scala:91)
[info]   Analysis:
[info]   HashSet(missingInRight: [6, 7])
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
[info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.$anonfun$testRequireCheckpointProtectionBeforeVersion$1(CheckpointProtectionTestUtilsMixin.scala:91)
[info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.$anonfun$testRequireCheckpointProtectionBeforeVersion$1$adapted(CheckpointProtectionTestUtilsMixin.scala:38)
[info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir(DeltaSQLTestUtils.scala:52)
[info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir$(DeltaSQLTestUtils.scala:50)
[info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.withTempDir(DeltaRetentionSuite.scala:38)
[info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir(DeltaSQLTestUtils.scala:35)
[info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir$(DeltaSQLTestUtils.scala:34)
[info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.withTempDir(DeltaRetentionSuite.scala:38)
[info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.testRequireCheckpointProtectionBeforeVersion(CheckpointProtectionTestUtilsMixin.scala:38)
[info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.testRequireCheckpointProtectionBeforeVersion$(CheckpointProtectionTestUtilsMixin.scala:30)
[info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.testRequireCheckpointProtectionBeforeVersion(DeltaRetentionSuite.scala:38)
[info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.$anonfun$new$94(DeltaRetentionSuite.scala:819)
```

**Comment by andreaschat-db** [comment]
> @andreaschat-db, could you help with the `Metadata cleanup respects requireCheckpointProtectionBeforeVersion` test failure, please?
> 
> I couldn't find any info in Delta protocol about checkpointProtection table feature
> 
> ```
> [info] - Metadata cleanup respects requireCheckpointProtectionBeforeVersion *** FAILED ***
> [info]   HashSet(10, 14, 6, 9, 13, 12, 7, 11, 8, 15) did not equal HashSet(10, 14, 9, 13, 12, 11, 8, 15) (CheckpointProtectionTestUtilsMixin.scala:91)
> [info]   Analysis:
> [info]   HashSet(missingInRight: [6, 7])
> [info]   org.scalatest.exceptions.TestFailedException:
> [info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
> [info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
> [info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
> [info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
> [info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.$anonfun$testRequireCheckpointProtectionBeforeVersion$1(CheckpointProtectionTestUtilsMixin.scala:91)
> [info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.$anonfun$testRequireCheckpointProtectionBeforeVersion$1$adapted(CheckpointProtectionTestUtilsMixin.scala:38)
> [info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir(DeltaSQLTestUtils.scala:52)
> [info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir$(DeltaSQLTestUtils.scala:50)
> [info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.withTempDir(DeltaRetentionSuite.scala:38)
> [info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir(DeltaSQLTestUtils.scala:35)
> [info]   at org.apache.spark.sql.delta.test.DeltaSQLTestUtils.withTempDir$(DeltaSQLTestUtils.scala:34)
> [info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.withTempDir(DeltaRetentionSuite.scala:38)
> [info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.testRequireCheckpointProtectionBeforeVersion(CheckpointProtectionTestUtilsMixin.scala:38)
> [info]   at org.apache.spark.sql.delta.CheckpointProtectionTestUtilsMixin.testRequireCheckpointProtectionBeforeVersion$(CheckpointProtectionTestUtilsMixin.scala:30)
> [info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.testRequireCheckpointProtectionBeforeVersion(DeltaRetentionSuite.scala:38)
> [info]   at org.apache.spark.sql.delta.DeltaRetentionSuite.$anonfun$new$94(DeltaRetentionSuite.scala:819)
> ```

Hi @felipepessoto, please check the doc in TableFeature. AFAIU, your PR is changing which checkpoints are removed and this changes the expectations of the test.

**Comment by felipepessoto** [comment]
@andreaschat-db, I fixed it, could you please review it?

**Review by andreaschat-db — COMMENTED** [review]
Hi @felipepessoto, thank you for looking at this. I left a couple of comments. However, I am a bit confused about what is exactly the issue we are trying to fix. AFAIU, the `BufferingLogDeletionIterator` is called with a max version. Isn't it guaranteed that at maxVersion + 1 there is a checkpoint? If so, what is the scenario that this can go wrong? Is there a case where we may stop earlier than maxVersion?

**Comment by felipepessoto** [comment]
> Hi @felipepessoto, thank you for looking at this. I left a couple of comments. However, I am a bit confused about what is exactly the issue we are trying to fix. AFAIU, the `BufferingLogDeletionIterator` is called with a max version. Isn't it guaranteed that at maxVersion + 1 there is a checkpoint? If so, what is the scenario that this can go wrong? Is there a case where we may stop earlier than maxVersion?

@andreaschat-db currently we remove the expired files as long they meet the maxVersion and maxTimestamp requirements. The problem is if we have the following:

- Expired: 0.json-5.json 
- Non-expired: 6.json-10.json + 10.checkpoint

The cleanup deletes 0-5, and the versions 6-9 are not expired, but can't be queried because they depend on 0-5 json files to build the Snapshot.
This is a known issue, the protocol has a suggestion to always keep the last expired checkpoint: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#metadata-cleanup. It was my initial implementation, but then I found it causes issues with the checkpointProtection, because it keeps logs files that are not strictly required, so I made more changes to keep only the files we really need.

Basically, I only flush the buffer when I find a checkpoint. Some example:

- Expired: 0.json-5.json 
- Non-expired: 6.json-10.json + 10.checkpoint
- Result: Don't delete anything

- Expired: 0.json-15.json + 10.checkpoint
- Non-expired: 16.json-20.json + 20.checkpoint
- Result: Deletes 0.json to 9.json

- Expired: 0.json-19.json + 10.checkpoint
- Non-expired: 20.json + 20.checkpoint
- Result: Deletes 0.json to 19.json + 10.checkpoint.  (in my initial implementation I was keeping versions starting from 10, the latest expired checkpoint)

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala [hunk 1]
```diff
@@ -856,24 +856,25 @@ object DeltaHistoryManager extends DeltaLogging {
      */
     private def queueFilesInBuffer(): Unit = {
       var continueBuffering = true
-      while (continueBuffering) {
-        if (!underlying.hasNext) {
-          flushBuffer()
-          return
-        }
-
+      while (continueBuffering && underlying.hasNext) {
```
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala:859]: We only want to flush when we find a checkpoint, if the underlying ended we want to discard the items in the buffer.

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala [hunk 2]
```diff
@@ -856,24 +856,25 @@ object DeltaHistoryManager extends DeltaLogging {
...
         var currentFile = underlying.next()
         require(currentFile != null, "FileStatus iterator returned null")
         if (needsTimeAdjustment(currentFile)) {
           currentFile = new FileStatus(
             currentFile.getLen, currentFile.isDirectory, currentFile.getReplication,
             currentFile.getBlockSize, lastFile.getModificationTime + 1, currentFile.getPath)
-          maybeDeleteFiles.append(currentFile)
-        } else {
+        } else if (FileNames.isCheckpointFile(currentFile)
+          && (versionGetter(currentFile.getPath) > versionGetter(lastFile.getPath))) {
```
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala:867]: I can change, but I'm not sure if the result will be clear, not sure if this is what you are suggesting?:

`isFileVersionBiggerThanLastFileVersion(currentFile)`

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala [hunk 3]
```diff
@@ -713,20 +849,18 @@ class DeltaRetentionSuite extends QueryTest
       testRequireCheckpointProtectionBeforeVersion(
         createNumCommitsOutsideRetentionPeriod = 8,
         createNumCommitsWithinRetentionPeriod = 8,
-        createCheckpoints = Set(1),
+        createCheckpoints = Set(1, 8),
```
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:852]: I'm not sure what was the corner case tested here. What would be the other parameters?

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala [hunk 4]
```diff
@@ -613,29 +749,29 @@ class DeltaRetentionSuite extends QueryTest
       testRequireCheckpointProtectionBeforeVersion(
         createNumCommitsOutsideRetentionPeriod = 2,
         createNumCommitsWithinRetentionPeriod = 14,
-        createCheckpoints = Set(1),
+        createCheckpoints = Set(2),
```
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala]: Updated. For the 3rd case I also had to change expectedCommitsAfterCleanup to start from 0, since we don't have a checkpoint for version 2, the cleanup is required to keep checkpoint 1, and then because of protected checkpoint logic, we can't clean up 0 if 1 isn't deleted too

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala (hunk 2 above)
[the remark this answers is not in the document]
Comment (andreaschat-db) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala:867]: Yes `isFileVersionGreaterThanLastFileVersion`.

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (andreaschat-db) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:855]: As I recall, the idea was to have a single checkpoint close to the boundary. But now this is shadowed by checkpoint 8. Perhaps we could reproduce the same behaviour with something like:

```
        createNumCommitsOutsideRetentionPeriod = 1,
        createNumCommitsWithinRetentionPeriod = 15,
        createCheckpoints = Set(1),
        requireCheckpointProtectionBeforeVersion = 10,
        expectedCommitsAfterCleanup = (1 to 15),
        expectedCheckpointsAfterCleanup = Set(10))
```
  
  If that does not work we can leave it as it is.

**Review by andreaschat-db — APPROVED** [review]

**Comment by andreaschat-db** [comment]
@prakharjain09 could you also please have a look?

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:855]: The `expectedCheckpointsAfterCleanup` is Set(1,10) in that case. I'm leaving as is for now. The same for the below

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala [hunk 5]
```diff
@@ -713,20 +849,18 @@ class DeltaRetentionSuite extends QueryTest
...
         expectedCommitsAfterCleanup = (8 to 15),
-        // This is a bit weird. Cleanup should had created a checkpoint at 8.
-        expectedCheckpointsAfterCleanup = Set(10))
+        expectedCheckpointsAfterCleanup = Set(8, 10))
 
       testRequireCheckpointProtectionBeforeVersion(
         createNumCommitsOutsideRetentionPeriod = 8,
         createNumCommitsWithinRetentionPeriod = 8,
-        createCheckpoints = Set(0),
+        createCheckpoints = Set(0, 8),
```
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:863]: Same as https://github.com/delta-io/delta/pull/4146/files#r2097911433

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala (hunk 2 above)
[the remark this answers is not in the document]
Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: Done, thanks

**Comment by felipepessoto** [comment]
+ @allisonport-db , could we merge it before 4.0 release?

**Comment by raveeram-db** [comment]
@dhruvarya-db do you have some cycles to review this PR please?

**Comment by felipepessoto** [comment]
Hi @dhruvarya-db, let me know if you have any questions about this change. Thanks

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala [hunk 6]
```diff
@@ -856,28 +856,33 @@ object DeltaHistoryManager extends DeltaLogging {
...
         require(currentFile != null, "FileStatus iterator returned null")
         if (needsTimeAdjustment(currentFile)) {
           currentFile = new FileStatus(
             currentFile.getLen, currentFile.isDirectory, currentFile.getReplication,
             currentFile.getBlockSize, lastFile.getModificationTime + 1, currentFile.getPath)
-          maybeDeleteFiles.append(currentFile)
-        } else {
+        } else if (FileNames.isCheckpointFile(currentFile)
+          && isFileVersionGreaterThanLastFileVersion(currentFile)) {
+          // Only flush the buffer when find a checkpoint. This is because we don't want to delete
```
Comment (dhruvarya-db) [inline spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: IMO we should also check whether it is a complete checkpoint in the case of a multi-part checkpoint.

Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala:868]: Since multi-part checkpoint are deprecated, instead, can I check if it is not a multi-part checkpoint?

Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: @dhruvarya-db, since multi-part is deprecated, can I check if the checkpoint is not a multi-part checkpoint?

Comment (dhruvarya-db) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: V2 Checkpoints (which replace multi-part checkpoints) is still an opt-in feature. My fear is that with this fix, users will start expecting log cleanup to always retain a recreatable history but any incomplete multi-part checkpoint will break that.

Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: I'm actually saying the opposite, changing this:

```
        } else if (FileNames.isCheckpointFile(currentFile)
          && isFileVersionGreaterThanLastFileVersion(currentFile)) {
```

to this:

```
        } else if (FileNames.isCheckpointFile(currentFile)
          && isFileVersionGreaterThanLastFileVersion(currentFile)
          && IsNotAMultiPartCheckpoint(currentFile)) {
```


That means multi-part checkpoint won't flush the buffer.

Checking the complete multi-part checkpoint would tricky because we would need to accumulate them in a different buffer (a map per version?), instead of the `maybeDeleteFiles.append(currentFile)` below, and add them to the buffer at once, after the flush.

Comment (dhruvarya-db) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: Could this potentially result in us never doing a cleanup if a table only has multi-part checkpoints? To handle multi-part checkpoints, we could potentially reuse the multi-part checkpoint logic from [DeltaHistoryManager](https://github.com/delta-io/delta/blob/2d05055e8f43716e4c30e1b2da681b73fa154b9f/spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala#L412)

Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: Right, that would be the trade-off.
Yes I'm using the exact same logic, I created this method:

```
    def isSingleOrMultiPartComplete(fileName: FileStatus): Boolean = {
      val parts = FileNames.numCheckpointParts(fileName.getPath)
      if (parts.isEmpty) {
        true
      } else {
        // if we have a multi-part checkpoint, we need to check that all parts exist
        val checkpointVersion = FileNames.checkpointVersion(fileName)
        val numParts = parts.get
        val preCount = checkpointMap.getOrElse(checkpointVersion -> numParts, 0)
        val newCount = preCount + 1
        checkpointMap.put(checkpointVersion -> numParts, newCount)
        numParts == newCount
      }
    }
```

And changed the if to:

```
} else if (FileNames.isCheckpointFile(currentFile)
          && isSingleOrMultiPartComplete(currentFile)) {
```

The problem is, when isSingleOrMultiPartComplete finally returns true, when currentFile is the last part, all the previous parts are already in the `maybeDeleteFiles`.

I can handle this but will be ugly. I need to keep a buffer of all parts of the last multi-part checkpoint, and only add it to `maybeDeleteFiles` when I find it is complete, or the next file is not part of that same multi-part checkpoint, meaning the checkpoint is incomplete. Let me try that

Comment (felipepessoto) [reply spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: @dhruvarya-db, I updated it to support multi-part checkpoint

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala [hunk 7]
```diff
@@ -856,23 +859,39 @@ object DeltaHistoryManager extends DeltaLogging {
...
+      while (continueBuffering && underlying.hasNext) {
         var currentFile = underlying.next()
         require(currentFile != null, "FileStatus iterator returned null")
         if (needsTimeAdjustment(currentFile)) {
           currentFile = new FileStatus(
             currentFile.getLen, currentFile.isDirectory, currentFile.getReplication,
             currentFile.getBlockSize, lastFile.getModificationTime + 1, currentFile.getPath)
           maybeDeleteFiles.append(currentFile)
+        } else if (FileNames.isCheckpointFile(currentFile)) {
+          // Only flush the buffer when find a checkpoint. This is because we don't want to delete
```
Comment (dhruvarya-db) [inline spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: [nit] 
```suggestion
          // Only flush the buffer when we find a checkpoint. This is because we don't want to delete
```

File: spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala [hunk 8]
```diff
@@ -856,23 +859,39 @@ object DeltaHistoryManager extends DeltaLogging {
...
-
+      while (continueBuffering && underlying.hasNext) {
         var currentFile = underlying.next()
         require(currentFile != null, "FileStatus iterator returned null")
         if (needsTimeAdjustment(currentFile)) {
           currentFile = new FileStatus(
             currentFile.getLen, currentFile.isDirectory, currentFile.getReplication,
             currentFile.getBlockSize, lastFile.getModificationTime + 1, currentFile.getPath)
           maybeDeleteFiles.append(currentFile)
+        } else if (FileNames.isCheckpointFile(currentFile)) {
```
Comment (dhruvarya-db) [inline spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala]: For extra precaution, we should also ignore any checkpoint files with size 0

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala [hunk 9]
```diff
@@ -509,6 +509,142 @@ class DeltaRetentionSuite extends QueryTest
...
+            }
+          }
+        } else {
+          spark.sql(sqlCommand).collect()
+        }
+      }
+    }
+    }
+  }
+  }
```
Comment (dhruvarya-db) [inline spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:646]: Let's also add a few test cases for complete and incomplete multi-part checkpoints?

**Review by dhruvarya-db — COMMENTED** [review]
Thanks for fixing this @felipepessoto ! The change makes sense to me, left a couple of suggestions.

File: spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala (hunk 9 above)
Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:646]: The `cleanup does not delete the checkpoint if it is required by non-expired versions.` covers the multi-part complete case. I added "cleanup does not delete the JSON logs if the multi-part checkpoint is incomplete."

Comment (felipepessoto) [reply spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala:646]: @dhruvarya-db, please let me know if it looks good now

Thanks.

**Comment by felipepessoto** [comment]
Thanks @dhruvarya-db. I'm not sure what are the next steps to get it merged to master and if I should open a PR to 4.0 branch?

**Comment by dhruvarya-db** [comment]
Looks like 4.0.0 has already been [released](https://github.com/delta-io/delta/releases). @allisonport-db does it make sense to backport this to the 4.0 branch? It might be useful in case there is another 4.0 maintenance release?

**Comment by felipepessoto** [comment]
Hi @allisonport-db, could you help with the merge, and should I create a PR to cherry pick it to 4.0?

Thanks

**Comment by felipepessoto** [comment]
Gentle ping @allisonport-db

**Comment by felipepessoto** [comment]
@scottsand-db could you help with merge and help decide if it make sense to backport this to the 4.0 branch?

**Comment by scottsand-db** [comment]
@dhruvarya-db and @felipepessoto -- is this considered a bug or correctness fix? Thats' the only reason we would want to backport it to the 4.0 branch

**Comment by felipepessoto** [comment]
Hard to judge since protocol is not strict about it, it only provides recommendation. But the consequences can be severe, as data loss since user can't reconstruct old version.

**Comment by felipepessoto** [comment]
@vkorukanti, @scottsand-db tests are all green after the rebase

**Comment by felipepessoto** [comment]
Thanks @vkorukanti

@scottsand-db, since it is not following protocol recommendation and can cause data loss, I believe it fits on bug fix category. I created a PR for 4.0 branch: https://github.com/delta-io/delta/pull/4784
