### PR TITLE
[Spark][2.4] Fix flaky test suite DeltaSourceDeletionVectorsSuite

### LINKED ISSUE #1982: [BUG][Spark] Fix flaky test suite `org.apache.spark.sql.delta.DeltaSourceDeletionVectorsSuite`
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem

Failed test `subsequent DML commands are processed correctly in a batch - INSERT->UPDATE - List((ignoreChanges,true)) *** FAILED ***`

CI runs: https://github.com/delta-io/delta/actions/runs/5835475304/job/15827113787, https://github.com/delta-io/delta/actions/runs/5868780845/job/15912353282?pr=1950

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by larsk-db**
## Description

(Cherrypick of 67c4b983088ae7e2d1d5cac6403792eb9ba35385 to branch-2.4)

- Remove flakiness from a previously flaky test case, by ensuring that the stream is stopped processing before running new DML commands on the source table.

Fixes #1982

## How was this patch tested?

Testing-only PR.

## Does this PR introduce _any_ user-facing changes?

No.

### CODE REVIEW

File: core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala [hunk 1]
```diff
@@ -157,15 +158,22 @@ trait DeltaSourceDeletionVectorTests extends StreamTest with DeletionVectorsTest
     val shouldFailAfterCommands = expectations.exists(_.isInstanceOf[ExpectFailure[_]])
 
     val baseActions: Seq[StreamAction] = Seq(
-      StartStream(
-        Trigger.ProcessingTime("10 seconds"),
-        new StreamManualClock(System.currentTimeMillis())),
-      AdvanceManualClock(10L * 1000L),
+      StartStream(Trigger.ProcessingTime(1000), clock),
+      AdvanceManualClock(1000L),
```
Comment (tdas) [inline core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:162]: this part is basically no different from before .. isnt it?

Comment (larsk-db) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:162]: Yeah, just got rid of some unnecessary large numbers.

Comment (larsk-db) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:162]: Makes it clearer imo that all the units match up as well.

Comment (tdas) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:162]: But the numbers themselves dont matter since its manual clock.. isnt it? just make sure.

Comment (tdas) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:162]: But the numbers themselves dont matter since its manual clock.. isnt it? just making sure.

File: core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala [hunk 2]
```diff
@@ -157,15 +158,22 @@ trait DeltaSourceDeletionVectorTests extends StreamTest with DeletionVectorsTest
...
       CheckAnswer((0 until 15): _*),
       AssertOnQuery { q =>
-        // Make sure we only processed a single batch since the initial data load.
```
Comment (tdas) [inline core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:166]: Which check was flaky here?

**Review by tdas — APPROVED** [review]

File: core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala (hunk 2 above)
Comment (larsk-db) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala:166]: The stream hadn't always stopped processing before we executed the 2 DML commands. So they'd sometimes end up together in the same batch and sometimes in two different batches, because they were processing even before the second increase of the clock. The thing that finally fixed it was adding the waiting for the stream to settle down before even starting on the DML commands.
