### PR TITLE
[Kernel] Fix incorrect load protocol and metadata time log

### LINKED ISSUE #3948: [BUG] [Kernel] Incorrect load protocol and metadata time log
[Here](https://github.com/delta-io/delta/blob/b39d5b328ffa8e1071fc6aab78cfb345c8f2d8f7/kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java#L546) we intend to log the duration of how long it took LogReplay to load the protocol and metadata.

However, the `startTimeMillis` is declared _after_ the LogReplay object has been created, and the P & M are loading in the constructor of LogReplay. Thus, we are not correctly measuring the time it took to load the P & M.

The ask: please fix this so that we correctly log the actual logReplay time.

### PR DESCRIPTION
**Pull request by anton-erofeev**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

## Description
Resolves #3948 
Fixed incorrect load protocol and metadata time log

## How was this patch tested?
Unit tests

## Does this PR introduce _any_ user-facing changes?
No

### CODE REVIEW

**Review by vkorukanti — APPROVED** [review]

File: kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java [hunk 1]
```diff
@@ -534,8 +536,6 @@ private SnapshotImpl createSnapshot(LogSegment initSegment, Engine engine) {
             initSegment,
             Optional.ofNullable(latestSnapshotHint.get()));
 
-    long startTimeMillis = System.currentTimeMillis();
```
Comment (scottsand-db) [inline kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java:537]: btw, it would have been more accurate to move the logger.info here, too. Now we are also including `assertLogFilesBelongToTable` in our time calculation

Comment (anton-erofeev) [reply kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java:537]: @scottsand-db good point, please see this pull request https://github.com/delta-io/delta/pull/3974
