### PR TITLE
Revert usages of Delta*Exception extending DeltaThrowable

### LINKED ISSUE #1086: [BUG][1.2.0] regression: scala DeltaAnalysisException exposed to user in pyspark
### Describe the problem

In `1.2.0` we introduced [DeltaSharedExceptions](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/DeltaSharedExceptions.scala), and replaced `org.apache.spark.sql.AnalysisException`s with `DeltaAnalysisException`. However, Spark 3.2 [doesn't capture](https://github.com/apache/spark/blob/branch-3.2/python/pyspark/sql/utils.py#L85) these Scala exceptions in pyspark as it does for `AnalysisException`s. This is [fixed](https://github.com/apache/spark/blob/master/python/pyspark/sql/utils.py#L156) for Spark 3.3 and master. So instead we see the weird java error shown below.

#### Steps to reproduce

See #1081

#### Observed results

```
py4j.protocol.Py4JJavaError: An error occurred while calling o41.load.
: org.apache.spark.sql.delta.DeltaAnalysisException: `/tmp/table_exists` is not a Delta table.
	at org.apache.spark.sql.delta.DeltaErrors$.notADeltaTableException(DeltaErrors.scala:281)
	at org.apache.spark.sql.delta.catalog.DeltaTableV2.toBaseRelation(DeltaTableV2.scala:169)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.$anonfun$createRelation$4(DeltaDataSource.scala:187)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:120)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:118)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.recordFrameProfile(DeltaDataSource.scala:50)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:164)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:243)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

#### Expected results

We should see a `org.apache.spark.sql.AnalysisException` _python_ exception.

Run with 1.1.0 we see...
```
pyspark.sql.utils.AnalysisException: `/tmp/table_exists` is not a Delta table.
```

### Environment information

* Delta Lake version: 1.2.0
* Spark version: 3.2
* Scala version: 2.12

### PR DESCRIPTION
**Pull request by vkorukanti**
## Description
Commit 59d5ea2 replaced the usage of `AnalysisException` with `DeltaAnalysisException`. This caused the Python API exception conversion to not work. Earlier the exception `AnalysisException` used to be convertd to PySpark's `AnalysisException` (code is [here](https://github.com/databricks/runtime/blob/master/python/pyspark/sql/utils.py#L156)). With 59d5ea2, exception `DeltaAnalysisException` is thrown directly as a Py4JError.

Revert the usage of `DeltaAnalysisException` to not break the Python API compatibility.

Summary of reverts.
* `DeltaAnalysisException` - Reverted in all production code. Only place this remains is in a disabled test in `DeltaErrorsSuite`
* `DeltaIllegalArgumentException` - This is used only in two helper methods (`copyIntoEncryptionSseCRequired` and `copyIntoEncryptionMasterKeyRequired`) in `DeltaErrors` which are not used anywhere in the production code.
* `DeltaIllegalStateException` - Used only in couple of places (`Checkpoints.scala`, `DeltaInvariantCheckerExec.scala`) which are reverted in this PR. Remaining uses are in utility method `DeltaErrors.failOnCheckpoint` which is not used anywhere in the production code.
* `DeltaColumnMappingUnsupportedException` - This is used in few places like when column rename not supported, generating manifest file, convert to delta and few schema change operations. These changes are not reverted. Let me know if this needs revert as well.

Resolves #1086

## How was this patch tested?
Locally.

```
(base) $ spark-3.2.1-bin-hadoop3.2 % pyspark --packages io.delta:delta-core_2.12:1.2.1-SNAPSHOT --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"


downloading file:~/.m2/repository/io/delta/delta-core_2.12/1.2.1-SNAPSHOT/delta-core_2.12-1.2.1-SNAPSHOT.jar ...

>>> df = spark.read.format("delta").load("/tmp/delta-table2234234")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 158, in load
    return self._df(self._jreader.load(path))
  File "/opt/anaconda3/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/opt/anaconda3/lib/python3.9/site-packages/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: `/tmp/delta-table2234234` is not a Delta table.
```

### CODE REVIEW

**Comment by tdas** [comment]
Have you reverted all usages of DeltaAnalysisException?
And i think you need to handle DeltaIllegalArgumenException

File: core/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala [hunk 1]
```diff
@@ -108,8 +108,8 @@ trait DeltaErrorsSuiteBase
     testUrls()
   }
 
-
-  test("test DeltaErrors OSS methods") {
+  // Disabled due to delta-io/delta/issue/1070
+  ignore("test DeltaErrors OSS methods") {
```
Comment (tdas) [inline core/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala:112]: this will be reenabled after fixing the other issue .. right?

Comment (vkorukanti) [reply core/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala:112]: Thats correct, but this PR is for 1.2.1 branch only.

**Comment by vkorukanti** [comment]
> Have you reverted all usages of DeltaAnalysisException? And i think you need to handle DeltaIllegalArgumenException

Updated the PR and also put the summary of what exceptions are reverted in the PR description.

**Comment by tdas** [comment]
thanks for the details in the description. this makes sense. 

why are the tests not running or failed?

**Review by tdas — APPROVED** [review]

**Comment by vkorukanti** [comment]
> why are the tests not running or failed?
There was an [issue](https://github.com/pyenv/pyenv-installer/issues/129#issuecomment-1086355727) with pyenv. It is resolved now. Re-triggered the tests.
