### PR TITLE
[Kernel] Fixed the issue with reading a list of JSON files when some files are empty

### LINKED ISSUE #2251: [Kernel] Test `DefaultJsonHandler` for empty JSON files
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

#2211 adds a test for reading empty parquet files (and fixes a bug in our `DefaultParquetReader`). We should test the same for the `DefaultJsonHandler`.

### Further details

We should test `DefaultJsonHandler.readJsonFiles(...)` with a file-list that includes empty JSON files in the middle of the list.

### PR DESCRIPTION
**Pull request by ilicmarkodb**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

## Description
Resolves #2251. Fixed the issue with reading a list of JSON files when some files are empty. Previously, the reading process would stop after encountering an empty file.

## How was this patch tested?
Test added to `DefaultJsonHandlerSuite.scala`.

## Does this PR introduce _any_ user-facing changes?
No.

### CODE REVIEW

**Comment by ilicmarkodb** [comment]
@allisonport-db can you please review?

**Comment by ilicmarkodb** [comment]
@uros-db can you please review?

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala [hunk 1]
```diff
@@ -373,6 +373,25 @@ class DefaultJsonHandlerSuite extends AnyFunSuite with TestUtils with DefaultVec
...
+      new StructType()
+        .add("c1", StringType.STRING)
+        .add("c3", StringType.STRING),
+      Optional.empty()
+    ).toSeq.map(batch => TestRow(batch.getRows.next))
+
+    val expResult = Seq(
+      TestRow("2-1", "2-3"),
+      TestRow("6-1", "6-3"),
+      TestRow("7-1", "7-3")
```
Comment (uros-db) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:389]: do we maybe want to align this test more with `test("read json files")`?

this is mostly regarding the contents of the `.json` files, otherwise lgtm

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala [hunk 2]
```diff
@@ -373,6 +373,25 @@ class DefaultJsonHandlerSuite extends AnyFunSuite with TestUtils with DefaultVec
     checkAnswer(actResult, expResult)
   }
 
+  test("read json files, some of which are empty") {
+    val testFiles = fsClient.listFrom(getTestResourceFilePath("json-files-with-empty/1.json"))
+    val actResult = jsonHandler.readJsonFiles(
+      testFiles,
+      new StructType()
+        .add("c1", StringType.STRING)
+        .add("c3", StringType.STRING),
```
Comment (uros-db) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:382]: it may be nice to see here something more like:

- StringType.STRING
- LongType.LONG)
- BooleanType.BOOLEAN

(this is also related to the other comment, comes down to json file structure and contents)

File: kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java [hunk 3]
```diff
@@ -117,18 +117,21 @@ public boolean hasNext() {
         // read.
         try {
           if (currentFileReader == null || (nextLine = currentFileReader.readLine()) == null) {
-
-            tryOpenNextFile();
-            if (currentFileReader != null) {
-              nextLine = currentFileReader.readLine();
+            // nextLine is here always null because, when currentFileReader is null, nextLine is also null
```
Comment (uros-db) [inline kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java:120]:
```suggestion
            // `nextLine` will initially be null because `currentFileReader` is guaranteed to be null.
```

**Review by uros-db — CHANGES_REQUESTED** [review]
left some minor comments

also, I would add another test such as:
```
test("read json files, all of which are empty")
```

of course accompanied by a couple of empty `json` files in a new dir:
`delta/kernel/kernel-defaults/src/test/resources/json-files-all-empty/`

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala [hunk 4]
```diff
@@ -373,6 +373,46 @@ class DefaultJsonHandlerSuite extends AnyFunSuite with TestUtils with DefaultVec
...
+  }
+
+  test("read json files, all empty") {
+    val testFiles = fsClient.listFrom(getTestResourceFilePath("json-files-all-empty/1.json"))
+    val actResult = jsonHandler.readJsonFiles(
+      testFiles,
+      new StructType()
+        .add("path", StringType.STRING)
+        .add("size", LongType.LONG)
+        .add("dataChange", BooleanType.BOOLEAN),
```
Comment (uros-db) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:407]: do we really need this, given that the files are empty anyway?

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala [hunk 5]
```diff
@@ -373,6 +373,46 @@ class DefaultJsonHandlerSuite extends AnyFunSuite with TestUtils with DefaultVec
...
+      TestRow("part-00000-0441e99a-c421-400e-83a1-212aa6c84c73-c000.snappy.parquet", 650L, true),
+      TestRow("part-00001-34c8c673-3f44-4fa7-b94e-07357ec28a7d-c000.snappy.parquet", 650L, true),
+      TestRow("part-00000-842017c2-3e02-44b5-a3d6-5b9ae1745045-c000.snappy.parquet", 649L, true),
+      TestRow("part-00001-e62ca5a1-923c-4ee6-998b-c61d1cfb0b1c-c000.snappy.parquet", 649L, true)
+    )
+
+    checkAnswer(actResult, expResult)
+  }
+
+  test("read json files, all empty") {
```
Comment (uros-db) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:400]:
```suggestion
  test("read json files, all of which are empty") {
```

**Review by uros-db — APPROVED** [review]
LGTM, minor comments left

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala (hunk 4 above)
Comment (ilicmarkodb) [reply kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:407]: I wanted the structure to remain the same across tests.

File: kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java [hunk 6]
```diff
@@ -117,18 +117,22 @@ public boolean hasNext() {
...
-              nextLine = currentFileReader.readLine();
+            // `nextLine` will initially be null because `currentFileReader` is guaranteed
+            // to be null
+            while (nextLine == null) {
+              tryOpenNextFile();
+              if (currentFileReader != null) {
+                nextLine = currentFileReader.readLine();
+              } else {
+                return false;
+              }
```
Comment (vkorukanti) [inline kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java:128]:
```suggestion
            // `nextLine` will initially be null because `currentFileReader` is guaranteed
            // to be null
            while (nextLine == null) {
              if (tryOpenNextFile()) {
                 return hasNext();
              }
            }
```

Comment (vkorukanti) [reply kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java:128]: basically modify the `tryOpenNextFile` to return true if a new file is opened, false otherwise. Depending upon that call the hasNext(). Simplifies the logic.

File: kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala [hunk 7]
```diff
@@ -373,6 +373,65 @@ class DefaultJsonHandlerSuite extends AnyFunSuite with TestUtils with DefaultVec
...
+  test("read json files from middle of directory, some of which are empty") {
+    val testFiles = fsClient.listFrom(getTestResourceFilePath("json-files-with-empty/5.json"))
+    val actResult = jsonHandler.readJsonFiles(
+      testFiles,
+      new StructType()
+        .add("path", StringType.STRING)
+        .add("size", LongType.LONG)
+        .add("dataChange", BooleanType.BOOLEAN),
+      Optional.empty()
+    ).toSeq.map(batch => TestRow(batch.getRows.next))
```
Comment (vkorukanti) [inline kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala:409]: seems like this code is common to all test. may be arrange the tests as follows:

```
Seq(
  (
     ..., // test files
     expectedResults
  ),
  (
   ...
  )
).foreach {
   case (testfiles, expResults) => 
      // test code.
}
   
```

**Review by vkorukanti — CHANGES_REQUESTED** [review]
Looks great! very minor comments.

**Review by vkorukanti — APPROVED** [review]
