### PR TITLE
[Kernel][Defaults] Support reading parquet files with legacy 3-level repeated types

### LINKED ISSUE #3082: [BUG][Kernel] Delta kernel read checkpoint parquet file failed with exception "list not found in optional group readerFeatures (LIST)"
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Describe the problem
When use delta kernel to read delta lake table encountered such an error
```
list not found in optional group readerFeatures (LIST) {
  repeated group bag {
    optional binary array (STRING);
  }
}
```

and the schema of parquet file is 
image

And I think delta kernel currently does not supports reading this legacy array type.

### Environment information

* Delta Lake version:
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by vkorukanti**
## Description
When legacy mode is enabled in Spark, array physical types are stored slightly different from the standard format.

Standard mode (default):
```
optional group readerFeatures (LIST) {
  repeated group list {
    optional binary element (STRING);
  }
}
```

When write legacy mode is enabled (`spark.sql.parquet.writeLegacyFormat = true`):
```
optional group readerFeatures (LIST) {
  repeated group bag {
    optional binary array (STRING);
  }
}
```

TODO: We need to handle the 2-level lists. Will post a separate PR. The challenge is with generating or finding the Parquet files with 2-level lists.

## How was this patch tested?
Added tests

Fixes #3082

### CODE REVIEW

File: kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ArrayColumnReader.java [hunk 1]
```diff
@@ -52,15 +55,38 @@ public ColumnVector getDataColumnVector(int batchSize) {
         return arrayVector;
     }
 
+    /**
```
Comment (vkorukanti) [inline kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ArrayColumnReader.java:58]: [same code](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala#L346) in Spark Parquet reader.

**Review by scottsand-db — APPROVED** [review]
